/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BottlesPackedResponse } from '../../models/bottles-packed-response';

export interface RetirerBoiteChariot$Params {
  index: number;
  indexBoite: number;
}

export function retirerBoiteChariot(http: HttpClient, rootUrl: string, params: RetirerBoiteChariot$Params, context?: HttpContext): Observable<StrictHttpResponse<BottlesPackedResponse>> {
  const rb = new RequestBuilder(rootUrl, retirerBoiteChariot.PATH, 'delete');
  if (params) {
    rb.path('index', params.index, {});
    rb.path('indexBoite', params.indexBoite, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BottlesPackedResponse>;
    })
  );
}

retirerBoiteChariot.PATH = '/api/emballage/chariots/{index}/boites/{indexBoite}';
