/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChariotsCountResponse } from '../../models/chariots-count-response';

export interface SupprimerChariot$Params {
  index: number;
}

export function supprimerChariot(http: HttpClient, rootUrl: string, params: SupprimerChariot$Params, context?: HttpContext): Observable<StrictHttpResponse<ChariotsCountResponse>> {
  const rb = new RequestBuilder(rootUrl, supprimerChariot.PATH, 'delete');
  if (params) {
    rb.path('index', params.index, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChariotsCountResponse>;
    })
  );
}

supprimerChariot.PATH = '/api/emballage/chariots/{index}';
