/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Type } from '../../models/type';

export interface ListTypes$Params {
}

export function listTypes(http: HttpClient, rootUrl: string, params?: ListTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Type>>> {
  const rb = new RequestBuilder(rootUrl, listTypes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Type>>;
    })
  );
}

listTypes.PATH = '/api/commercial/types';
