/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Vente } from '../../models/vente';
import { VenteType } from '../../models/vente-type';

export interface ListerVentes$Params {
  type?: VenteType;
  dateDebut?: string;
  dateFin?: string;
  vendeurId?: string;
}

export function listerVentes(http: HttpClient, rootUrl: string, params?: ListerVentes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Vente>>> {
  const rb = new RequestBuilder(rootUrl, listerVentes.PATH, 'get');
  if (params) {
    rb.query('type', params.type, {});
    rb.query('dateDebut', params.dateDebut, {});
    rb.query('dateFin', params.dateFin, {});
    rb.query('vendeurId', params.vendeurId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Vente>>;
    })
  );
}

listerVentes.PATH = '/api/ventes';
