/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Vente } from '../../models/vente';

export interface ObtenirVente$Params {
  id: string;
}

export function obtenirVente(http: HttpClient, rootUrl: string, params: ObtenirVente$Params, context?: HttpContext): Observable<StrictHttpResponse<Vente>> {
  const rb = new RequestBuilder(rootUrl, obtenirVente.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Vente>;
    })
  );
}

obtenirVente.PATH = '/api/ventes/{id}';
