/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Bouteille } from '../../models/bouteille';
import { BouteilleRequest } from '../../models/bouteille-request';

export interface FabriquerBouteille$Params {
      body: BouteilleRequest
}

export function fabriquerBouteille(http: HttpClient, rootUrl: string, params: FabriquerBouteille$Params, context?: HttpContext): Observable<StrictHttpResponse<Bouteille>> {
  const rb = new RequestBuilder(rootUrl, fabriquerBouteille.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Bouteille>;
    })
  );
}

fabriquerBouteille.PATH = '/api/industrial/bouteilles';
