/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminStats } from '../../models/admin-stats';

export interface AdminStats$Params {
}

export function adminStats(http: HttpClient, rootUrl: string, params?: AdminStats$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminStats>> {
  const rb = new RequestBuilder(rootUrl, adminStats.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminStats>;
    })
  );
}

adminStats.PATH = '/api/admin/stats';
