/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateSubscriptionRequest } from '../../models/create-subscription-request';
import { SubscriptionResponse } from '../../models/subscription-response';

export interface CreateWebhookSub$Params {
      body: CreateSubscriptionRequest
}

export function createWebhookSub(http: HttpClient, rootUrl: string, params: CreateWebhookSub$Params, context?: HttpContext): Observable<StrictHttpResponse<SubscriptionResponse>> {
  const rb = new RequestBuilder(rootUrl, createWebhookSub.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubscriptionResponse>;
    })
  );
}

createWebhookSub.PATH = '/api/webhooks/subscriptions';
