/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriptionResponse } from '../../models/subscription-response';

export interface ListWebhookSubs$Params {
}

export function listWebhookSubs(http: HttpClient, rootUrl: string, params?: ListWebhookSubs$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubscriptionResponse>>> {
  const rb = new RequestBuilder(rootUrl, listWebhookSubs.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SubscriptionResponse>>;
    })
  );
}

listWebhookSubs.PATH = '/api/webhooks/subscriptions';
