/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminStats {
  boitesEmballees: number;

  /**
   * Quantité par type (clé = Type)
   */
  stockBrut: {
[key: string]: number;
};
  ventesCount: number;
}
