/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Type } from '../models/type';
export interface Boite {
  id?: number;
  prix?: number;
  quantite?: number;
  type?: Type;
}
