/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Litrage } from '../models/litrage';
import { Produit } from '../models/produit';
export type Bouteille = Produit & {
'litrage'?: Litrage;
};

