/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ErrorResponse {
  error?: string;
  message?: string;
  path?: string;
  status?: number;
  timestamp?: string;
}
