/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from './event-type';

/**
 * Each possible value of `EventType`
 */
export const EVENT_TYPE: EventType[] = [
  'STOCK_CHANGED',
  'VENTE_AU_VENDEUR_CREATED',
  'VENTE_DU_VENDEUR_CREATED'
];