/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LigneRequest {
  prixUnitaire: number;
  produitId: string;
  quantite: number;
  sousTotal?: number;
  typeLigne: 'BOITE' | 'BOUTEILLE';
}
