/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from './role';

/**
 * Each possible value of `Role`
 */
export const ROLE: Role[] = [
  'Admin',
  'Agent_commercial',
  'Agent_industrielle',
  'Vendeur'
];