/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Role constants used by the application (exact casing important)
 */
export type Role = 'Admin' | 'Agent_commercial' | 'Agent_industrielle' | 'Vendeur';

