/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignupResponse {
  expiresAt?: string;
  roles?: Array<string>;
  token?: string;
  userId?: number;
  username?: string;
}
