/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignupRequest {
  email: string;
  nom: string;
  password: string;
  prenom: string;

  /**
   * Optionnel; par défaut Vendeur; Admin requis pour autre rôle
   */
  role?: string;
}
