/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubscriptionResponse {
  active?: boolean;
  eventTypes?: Array<'STOCK_CHANGED' | 'VENTE_AU_VENDEUR_CREATED' | 'VENTE_DU_VENDEUR_CREATED'>;
  id?: number;
  targetUrl?: string;
}
