/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Type } from './type';

/**
 * Each possible value of `Type`
 */
export const TYPE: Type[] = [
  'ZITBLAD',
  'ASSELIA',
  'kAULDA'
];