/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VenteDuVendeurLigne {
  prixUnitaire: number;
  produitId: string;
  quantite: number;
  sousTotal?: number;
}
