/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VenteAuVendeurLigne } from '../models/vente-au-vendeur-ligne';
export interface VenteAuVendeur {
  dateVente?: string;
  id?: string;
  lignes?: Array<VenteAuVendeurLigne>;
  montantTotal?: number;
  vendeurId?: string;
}
