/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VenteDuVendeurLigne } from '../models/vente-du-vendeur-ligne';
export interface VenteDuVendeur {
  dateVente?: string;
  id?: string;
  lignes?: Array<VenteDuVendeurLigne>;
  montantTotal?: number;
  vendeurId?: string;
}
