/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VenteType } from './vente-type';

/**
 * Each possible value of `VenteType`
 */
export const VENTE_TYPE: VenteType[] = [
  'AU_VENDEUR',
  'DU_VENDEUR'
];