/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LigneRequest } from '../models/ligne-request';
import { VenteType } from '../models/vente-type';
export interface VenteCreateRequest {
  lignes: Array<LigneRequest>;
  type: VenteType;
  vendeurId?: string;
}
