/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
export interface WebhookEvent {
  eventType: EventType;
  payload: {
[key: string]: any;
};
  timestamp: string;
}
