/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MouvementRequest } from '../../models/mouvement-request';
import { StockQuantiteResponse } from '../../models/stock-quantite-response';

export interface StockBrutDiminuer$Params {
      body: MouvementRequest
}

export function stockBrutDiminuer(http: HttpClient, rootUrl: string, params: StockBrutDiminuer$Params, context?: HttpContext): Observable<StrictHttpResponse<StockQuantiteResponse>> {
  const rb = new RequestBuilder(rootUrl, stockBrutDiminuer.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockQuantiteResponse>;
    })
  );
}

stockBrutDiminuer.PATH = '/api/stock-brute/diminuer';
