/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StockQuantiteResponse } from '../../models/stock-quantite-response';
import { Type } from '../../models/type';

export interface StockBrutQuantite$Params {
  type: Type;
}

export function stockBrutQuantite(http: HttpClient, rootUrl: string, params: StockBrutQuantite$Params, context?: HttpContext): Observable<StrictHttpResponse<StockQuantiteResponse>> {
  const rb = new RequestBuilder(rootUrl, stockBrutQuantite.PATH, 'get');
  if (params) {
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockQuantiteResponse>;
    })
  );
}

stockBrutQuantite.PATH = '/api/stock-brute/quantite';
