/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdminStats } from './models/admin-stats';
export type { AjouterBoiteRequest } from './models/ajouter-boite-request';
export type { Boite } from './models/boite';
export type { BoiteRequest } from './models/boite-request';
export type { BottlesPackedResponse } from './models/bottles-packed-response';
export type { Bouteille } from './models/bouteille';
export type { BouteilleRef } from './models/bouteille-ref';
export type { BouteilleRequest } from './models/bouteille-request';
export type { Chariot } from './models/chariot';
export type { ChariotsCountResponse } from './models/chariots-count-response';
export type { CreateSubscriptionRequest } from './models/create-subscription-request';
export type { ErrorResponse } from './models/error-response';
export type { EventType } from './models/event-type';
export type { LigneRequest } from './models/ligne-request';
export type { Litrage } from './models/litrage';
export type { LoginRequest } from './models/login-request';
export type { LoginResponse } from './models/login-response';
export type { MouvementRequest } from './models/mouvement-request';
export type { Produit } from './models/produit';
export type { Role } from './models/role';
export type { SignupRequest } from './models/signup-request';
export type { SignupResponse } from './models/signup-response';
export type { StockQuantiteResponse } from './models/stock-quantite-response';
export type { SubscriptionResponse } from './models/subscription-response';
export type { Type } from './models/type';
export type { Vente } from './models/vente';
export type { VenteAuVendeur } from './models/vente-au-vendeur';
export type { VenteAuVendeurLigne } from './models/vente-au-vendeur-ligne';
export type { VenteCreateRequest } from './models/vente-create-request';
export type { VenteDuVendeur } from './models/vente-du-vendeur';
export type { VenteDuVendeurLigne } from './models/vente-du-vendeur-ligne';
export type { VenteType } from './models/vente-type';
export type { WebhookEvent } from './models/webhook-event';
export type { WhoAmIResponse } from './models/who-am-i-response';
